---
title: "STOR634 - Lecture Notes"
output:
  pdf_document:
    latex_engine: xelatex
    template: default.tex
mainfont: Times New Roman
geometry: margin = 1in
header-includes:
   - \usepackage{tikz}
   - \usepackage{fleqn}
   - \usepackage{xcolor}
   - \setlength{\mathindent}{0pt}
---

## Lecture 1

### CBasic oncepts

1,
$\boldsymbol{\Pi-class}$
closed under finite intersections.
  i.e. $A,\ B \in \mathcal{A}, \implies A \cap B \in \mathcal{A}$  
  
2,
$\boldsymbol{\sigma-\cap-closed}$
closed under countable intersections.
  i.e. 
  $A_1,\ A_2,\ \dots \in \mathcal{A}, \implies \cap_{i=1}^{\infty} A_i \in \mathcal{A}$  
  
3,
$\boldsymbol{\cup-closed}$
closed under finite unions.
  i.e. $A,\ B \in \mathcal{A}, \implies A \cup B \in \mathcal{A}$  

4,
$\boldsymbol{\sigma-\cup-closed}$
closed under countable unions.
  i.e. 
  $A_1,\ A_2,\ \dots \in \mathcal{A}, \implies \cup_{i=1}^{\infty} A_i \in \mathcal{A}$  
  
5,
$\boldsymbol{\setminus-closed}$
closed under set differences
i.e. $A,\ B \in \mathcal{A}, \implies A \setminus B \in \mathcal{A}$    

6, 
**closed under complements**
i.e. $A \in \mathcal{A}, \implies A^c \in \mathcal{A}$  

### Important Concepts

$\boldsymbol{\sigma-field}$ / $\boldsymbol{\sigma-algebra}$ 
A collection of sets $\mathcal{F} \subseteq 2^\Omega$ is called a $\sigma$-field if the following 3 conditions are satisfied:   
(i) $\Omega \in \mathcal{F}$;   
(ii) $\mathcal{F}$ is closed under complements;   
(iii) $\mathcal{F}$ is closed under countable union.    



**field / algebra**
A class of subsets $\mathcal{A} \subseteq 2^\Omega$ is called a field or algebra if the following 3 conditions are satisfied:   
(i) $\Omega \in \mathcal{A}$;   
(ii) $\mathcal{A}$ is closed under complements;   
(iii) $\mathcal{A}$ is closed under finite unions. 


### Theorem

In the definition of $\sigma$-field we can replace (iii) with (iii)' $\mathcal{F}$ is closed under countable intersections.   
Similarly, in the definition of field, we can replace (iii) with (iii)' $\mathcal{A}$ is closed under finite intersections. 


### More Concepts

 $\mathcal{A}$ is called a **ring** if :  
(i) $\emptyset \in  \mathcal{A}$  
(ii)  $\mathcal{A}$ is closed under set difference  
(iii)  $\mathcal{A}$ is closed under finite unions

Remarks:   
If we replace "finite union" in definition of ring to "countable union" we get a $\sigma$-ring.  
$\mathcal{A}$ is a field $\implies$ $\mathcal{A}$ is a ring.  

$\mathcal{A}$ is called a **semi-ring** if:  
(i) $\emptyset \in  \mathcal{A}$  
(ii) $A,\ B \in \mathcal{A}, \implies B \setminus A$ is a finite union of disjoint sets from $\mathcal{A}$  
(iii) $\mathcal{A}$ is closed under finite intersections  


$\mathcal{A}$ is called a $\boldsymbol{\lambda-class}$ if :  
(i) $\Omega \in  \mathcal{A}$  
(ii) For any 2 sets $A, B \in \mathcal{A}$ with $A \subseteq B \implies B \setminus A \in \mathcal{A}$ is closed under set difference  
(iii) Suppose $A_1, A_2, \dots \in \mathcal{A}$ and further for all $i \neq j, \ A_i \cap A_j = \emptyset \implies \cup_{i=1}^{\infty} A_i \in \mathcal{A}$ 

### Theorem

1,
$\mathcal{A}$ is $\sigma-field \implies \mathcal{A}$ is a $\lambda-class$, algebra, $\sigma-ring$, ring, semi-ring.  
2, 
$\sigma-ring \implies$ ring $\implies$ semi-ring.  
3,
Field $\implies$ ring; field on a finite set $\implies \sigma-field$.  

### Theorem


Let I be an arbitrary index set and suppose $\mathcal{A}_i$ is a $\sigma-field$ for all $i \in I$. Then  $\mathcal{A}_I := \{ A \subset \Omega: A \in \mathcal{A}_i \ for\ every\ i \in I \} = \cap_{i \in I} \mathcal{A}_i$ is also a $\sigma-field$. Similar statement is true for rings, sigma-rings, fields, lambda-systems but NOT semi-rings.  


Let $\varepsilon \subset 2^\Omega$ be an arbitrary collection of sets. Then there exists a smallest sigma-field containing $\varepsilon$. Writing $\sigma(\varepsilon)$ for this sigma-field, this can be obtained via $\sigma(\varepsilon) = \cap_{\mathcal{A} \subset 2^\Omega,\ \mathcal{A}\ is\ a\ \sigma-field,\ \mathcal{A} \supseteq \varepsilon} \mathcal{A}$. This will be called the sigma-field generated by $\varepsilon$. Similarly for lambda-system generated by $\varepsilon$.

## Lecture 2  






